### PR TITLE
Refactor: Gateway functions to get Gateway address dynamically

### PR DESCRIPTION
**Pull request by lukema95**
issue: #201 

Update:
1. Make the gateway contract parameter optional in the task command line.
2. Extend ZetaChainClient to support reading gateway contract addresses from the contract configuration file. Add a 'contracts' field to store the contract information read from the file.
3. If no gateway parameter is provided, ZetaChainClient will use the Gateway contract address from the configuration file. For localhost/localnet environments, the gateway parameter must be passed either in the task command line or through the contracts field in ZetaChainClient.

## Summary by CodeRabbit

- **New Features**
	- Enhanced flexibility in various functions by making the `gatewayEvm` and `gatewayZetaChain` parameters optional.
	- Introduced new interfaces for address management in the `ZetaChainClient`.

- **Bug Fixes**
	- Improved error handling for gateway address retrieval across multiple functions.

- **Chores**
	- Updated dependency versions in the project configuration to reflect recent changes.

- **Documentation**
	- Updated task definitions to remove default values for certain parameters, requiring explicit user input.
	- Modified task configurations to dynamically use the current network context.

### CODE REVIEW

**Comment by lukema95** [comment]
@fadeev pls review

**Comment by fadeev** [comment]
Looks good so far 👍

**Comment by fadeev** [comment]
@coderabbitai review

**Comment by fadeev** [comment]
@lukema95 ready to merge once the conflicts are resolved.

**Comment by lukema95** [comment]
> @lukema95 ready to merge once the conflicts are resolved.

done

**Review by fadeev — APPROVED** [review]

**Comment by fadeev** [comment]
@lukema95 I've made a pre-release with these changes to make it easier to test changes to the UniversalKit:

https://github.com/zeta-chain/toolkit/releases/tag/v13.0.0-rc9

**Pull request merged**
