### PR TITLE
feat: Swap helpers to always swap through ZETA

### PR DESCRIPTION
**Pull request by lukema95**
Related: #153 

## Summary by CodeRabbit

- **New Features**
	- Introduced a new error type, `InvalidPathLength`, for improved error handling during token path validation.
	- Added a liquidity check functionality to ensure sufficient liquidity before executing token swaps.
	- Enhanced the token swapping process with a fallback mechanism including the wrapped ZETA token when liquidity is insufficient.
	- Added a new function to calculate minimum output amounts for swap operations, improving user experience in decentralized finance transactions.

- **Bug Fixes**
	- Improved error reporting for token path length issues, ensuring clearer feedback for users.

### CODE REVIEW

**Comment by lukema95** [comment]
Since the current pool of 0/0 liquidity is recognized as not existing, I can only test with the pool of liquidity(MATIC.AMOY / tBNB).
I used the following two different pieces of code to test ease of use and deployed two contracts. The complete code is in [SwapToAnyToken](https://github.com/lukema95/example-contracts/blob/swap-optimize/omnichain/swap/contracts/SwapToAnyToken.sol) and [SwapToAnySwapDirectly](https://github.com/lukema95/example-contracts/blob/swap-optimize/omnichain/swap/contracts/SwapToAnyTokenDirectly.sol).

# SwapToAnyTokenDirectly
The first code is as follows, it gets the optimal output quantity first, then call `swapExactTokensForTokensDirectly` directly:
```solidity
function onCrossChainCall(
        zContext calldata context,
        address zrc20,
        uint256 amount,
        bytes calldata message
    ) external virtual override onlySystem(systemContract) {
        // others codes...

        uint256 amountIn = params.withdraw ? amount - inputForGas : amount;
        uint256 minOutAmount = getMintOutAmount(zrc20, params.target, amountIn);

        uint256 outputAmount = SwapHelperLib.swapExactTokensForTokensDirectly(
            systemContract,
            zrc20,
            params.withdraw ? amount - inputForGas : amount,
            params.target,
            minOutAmount
        );

        if (params.withdraw) {
            IZRC20(gasZRC20).approve(params.target, gasFee);
            IZRC20(params.target).withdraw(params.to, outputAmount);
        } else {
            IWETH9(params.target).transfer(address(uint160(bytes20(params.to))), outputAmount);
        }
    }

    function getMintOutAmount(address zrc20, address target, uint256 amountIn) public view returns (uint256 minOutAmount) {
        address[] memory path;

        path = new address[](2);
        path[0] = zrc20;
        path[1] = target;
        uint[] memory amounts1 = UniswapV2Library.getAmountsOut(systemContract.uniswapv2FactoryAddress(), amountIn, path);

        path = new address[](3);
        path[0] = zrc20;
        path[1] = systemContract.wZetaContractAddress();
        path[2] = target;
        uint[] memory amounts2 = UniswapV2Library.getAmountsOut(systemContract.uniswapv2FactoryAddress(), amountIn, path);

        minOutAmount = amounts1[amounts1.length - 1] > amounts2[amounts2.length - 1] ? amounts1[amounts1.length - 1] : amounts2[amounts2.length - 1];
    }
```
Since the liquidity of the route ` WZETA/tBNB -> WZETA / MATIC.AMOY ` is better than the liquidity of the route ` MATIC.AMOY/tBNB `, the transaction will fail.
```bash
# Swap tBNB(BSC Testnet) -> MATIC.AMOY
# Contract: 0x7D9D2b200D3d2FF65Cc1AA1F2Acc70539b424843

npx hardhat interact \
--contract 0x7D9D2b200D3d2FF65Cc1AA1F2Acc70539b424843 \
--network bsc_testnet \
--amount 0.1 \
--target-token 0x777915D031d1e8144c90D025C594b3b8Bf07a08d        \
--recipient 0x6093537Aa6C8C8bf4705bda40aC9193977208B39 \
--withdraw false

🚀 Successfully broadcasted a token transfer transaction on bsc_testnet network.
📝 Transaction hash: 0x7f3313fda5bc429c0a3a92108c802dbf5917ea2cebef376486425a09cc1ecb46

npx hardhat cctx 0x7f3313fda5bc429c0a3a92108c802dbf5917ea2cebef376486425a09cc1ecb46
✓ CCTXs on ZetaChain found.

⠼ 0xe04e4ca4dde03908b307ee199b9bdca00f3acf9ce6cffdcd34234367198b88bf: 97 → 7001: PendingRevert (contract call failed: meth
od 'depositAndCall', contract '0xEdf1c3275d13489aCdC6cD6eD246E72458B8795B', args: [{[96 147 83 122 166 200 200 191 71 5 18
9 164 10 201 25 57 119 32 139 57] 0x0000000000000000000000000000000000000000 97} 0xd97B1de3619ed2c6BEb3860147E30cA8A7dC989
1 100000000000000000 0x7D9D2b200D3d2FF65Cc1AA1F2Acc70539b424843 [0 0 0 0 0 0 0 0 0 0 0 0 119 121 21 208 49 209 232 20 76 1
44 208 37 197 148 179 184 191 7 160 141 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 96 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 20 96 147 83 
122 166 200 200 191 71 5 189 164 10 201 25 57 119 32 139 57 0 0 0 0 0 0 0 0 0 0 0 0]]: execution reverted: ret 0x08c379a00
00000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000
0002b556e69737761705632526f757465723a20494e53554646494349454e545f4f55545055545f414d4f554e540000000000000000000000000000000
00000000000: evm transaction execution failed)

Decode the error msg:
Error("UniswapV2Router: INSUFFICIENT_OUTPUT_AMOUNT")

```

# SwapToAnyToken
The second type of code is the following, which calls the `swapExactTokensForTokens` method, so it will always get the optimal route.
```solidity
function onCrossChainCall(
        zContext calldata context,
        address zrc20,
        uint256 amount,
        bytes calldata message
    ) external virtual override onlySystem(systemContract) {
        // others codes...

        uint256 amountIn = params.withdraw ? amount - inputForGas : amount;
        uint256 minOutAmount = getMintOutAmount(zrc20, params.target, amountIn);
        
        uint256 outputAmount = SwapHelperLib.swapExactTokensForTokens(
            systemContract,
            zrc20,
            params.withdraw ? amount - inputForGas : amount,
            params.target,
            minOutAmount
        );

        if (params.withdraw) {
            IZRC20(gasZRC20).approve(params.target, gasFee);
            IZRC20(params.target).withdraw(params.to, outputAmount);
        } else {
            IWETH9(params.target).transfer(address(uint160(bytes20(params.to))), outputAmount);
        }
    }

    function getMintOutAmount(address zrc20, address target, uint256 amountIn) public view returns (uint256 minOutAmount) {
        address[] memory path;

        path = new address[](2);
        path[0] = zrc20;
        path[1] = target;
        uint[] memory amounts1 = UniswapV2Library.getAmountsOut(systemContract.uniswapv2FactoryAddress(), amountIn, path);

        path = new address[](3);
        path[0] = zrc20;
        path[1] = systemContract.wZetaContractAddress();
        path[2] = target;
        uint[] memory amounts2 = UniswapV2Library.getAmountsOut(systemContract.uniswapv2FactoryAddress(), amountIn, path);

        minOutAmount = amounts1[amounts1.length - 1] > amounts2[amounts2.length - 1] ? amounts1[amounts1.length - 1] : amounts2[amounts2.length - 1];
    }

```
The above transaction will be called successfully:
```bash
# Swap tBNB(BSC Testnet) -> MATIC.AMOY
# Contract: 0x57b7ABbD0459e6f9D96326d9D23AF775bd3752c2

npx hardhat interact \
--contract 0x57b7ABbD0459e6f9D96326d9D23AF775bd3752c2 \
--network bsc_testnet \
--amount 0.1 \
--target-token 0x777915D031d1e8144c90D025C594b3b8Bf07a08d	 \
--recipient 0x6093537Aa6C8C8bf4705bda40aC9193977208B39 \
--withdraw false

🚀 Successfully broadcasted a token transfer transaction on bsc_testnet network.
📝 Transaction hash: 0x839d40bbefcd98484d0c0fa521a9fd04e81e8718532c3a74e8b6a1dc2146f928

npx hardhat cctx 0x839d40bbefcd98484d0c0fa521a9fd04e81e8718532c3a74e8b6a1dc2146f928
✓ CCTXs on ZetaChain found.

✓ 0x10c107ec178c43eeeb42e8cd33028735bfd5cc624eef2b8899c56a529fc7e9c0: 97 → 7001: OutboundMined (Remote omnichain contract call completed)


```

**Comment by lukema95** [comment]
@fadeev pls review.

**Comment by fadeev** [comment]
@lukema95 I think this is looking good! Should we put `getMintOutAmount` into the toolkit as well, so a user could just import it?

**Comment by lukema95** [comment]
> @lukema95 I think this is looking good! Should we put `getMintOutAmount` into the toolkit as well, so a user could just import it?

No problem, I'll finish it later.

**Comment by lukema95** [comment]
> @lukema95 please, update, so we can review and merge. Thanks!

Added it.

**Comment by fadeev** [comment]
@andresaiello please, review. Thanks!

**Review by andresaiello — APPROVED** [review]

**Pull request merged**
